project:
  type: website

website:
  title: "Blog Jesse van Elteren"
  site-url: https://jvanelteren.github.io/blog/
  description: "Data science posts"
  google-analytics: "UA-1302238-4"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: united
      # united
      dark: darkly
    css: styles.css


